<?php
/* @var $block \Eloom\Widgets\Block\Widget\BestSellers */

if ($block->getProductCollection() && $block->getProductCollection()->getSize()):
	$items = $block->getProductCollection()->getItems();
	$alias = 'widget-best-sellers-' . $this->getAlias();
	$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
?>
<div class="block-title">
	<strong role="heading" aria-level="2"><?= $block->escapeHtml(__('Best Sellers')) ?></strong>
</div>
<div class="block-content">
		<div id="<?php echo $alias; ?>" class="owl-carousel owl-theme">
			<?php foreach ($items as $_item):?>
				<div class="product-item">
					<div class="product-item-info">
						<a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
						   class="product-item-photo">
							<?= $block->getImage($_item, 'category_page_grid')->toHtml() ?>
						</a>
						<div class="product-item-details">
							<strong class="product-item-name">
								<a title="<?= $block->escapeHtml($_item->getName()) ?>"
								   href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
								   class="product-item-link">
									<?= $block->escapeHtml($_item->getName()); ?>
								</a>
							</strong>

							<?= $block->getProductPrice($_item); ?>

							<?php if ($templateType):?>
								<?= $block->getReviewsSummaryHtml($_item, $templateType); ?>
							<?php endif; ?>
						</div>
					</div>
				</div>
			<?php endforeach ?>
		</div>
	</div>

<script type="text/x-magento-init">
  {
      "<?php echo "#{$alias}"?>": {
          "EloomOwlCarousel": {
              "loop": true,
							"margin": 10,
							"dots": false,
							"rewindNav": true,
							"nav": true,
							"navText": ["", ""],
						  "animateOut": "fadeOut",
              "responsive": {
								"0": {
									"items": 1
								},
								"600": {
									"items": 2
								},
								"1000": {
									"items": 4
								}
							}
          }
      }
  }
</script>
<?php endif; ?>