<?php
/* @var $block \Eloom\Widgets\Block\Widget\BestSellers */

if ($block->getProductCollection() && $block->getProductCollection()->getSize()):
$items = $block->getProductCollection()->getItems();
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
$type = 'widget-product-grid';
$alias = 'grid-' . $block->getAlias();
?>
	<div class="widget block-products grid" id="<?=$alias?>">
		<div class="block-title">
				<strong role="heading" aria-level="2"><?= $block->escapeHtml(__('Best Sellers')) ?></strong>
		</div>
		<div class="block-content">
				<div class="products-grid grid">
					<ol class="product-items <?= $type ?>">
						<?php foreach ($items as $_item) :?>
							<li class="product-item">
								<div class="product-item-info">
									<a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
									   class="product-item-photo">
										<?= $block->getImage($_item, 'category_page_grid')->toHtml() ?>
									</a>
									<div class="product-item-details">
										<strong class="product-item-name">
											<a title="<?= $block->escapeHtml($_item->getName()) ?>"
											   href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
											   class="product-item-link">
												<?= $block->escapeHtml($_item->getName()) ?>
											</a>
										</strong>
										<?= $block->getProductPrice($_item, $type) ?>
									</div>
								</div>
							</li>
						<?php endforeach ?>
					</ol>
			</div>
			<?= $block->getPagerHtml() ?>
		</div>
	</div>

	<script type="text/x-magento-init">
	{
			"#<?= $alias ?>": {
	          "Eloom_Widgets/js/product/grid": {}
	    }
	}
	</script>
<?php endif; ?>