<div class="block widget widget-onsale-products products carousel"
     loading="lazy"
     data-eloom-widget data-uri="/eloomwidgets/product/onSale"
     data-params='<?= $this->getJsonConfig()?>'>
	<div class="loader-spinners">
		<span class="loader-spinners__child"></span>
		<span class="loader-spinners__child"></span>
		<span class="loader-spinners__child"></span>
		<span class="loader-spinners__child"></span>
	</div>
</div>