<div class="block widget block-best-sellers grid"
     loading="lazy"
     data-eloom-widget data-uri="/eloomwidgets/product/bestSellers"
     data-params='<?= $this->getJsonConfig()?>'>
	<div class="loader-spinners">
		<span class="loader-spinners__child"></span>
		<span class="loader-spinners__child"></span>
		<span class="loader-spinners__child"></span>
		<span class="loader-spinners__child"></span>
	</div>
</div>