<?php
use Magento\Framework\App\Action\Action;

/* @var $block \Eloom\Widgets\Block\Widget\ProductsByCategory */
?>

<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())): ?>
	<?php
	$type = 'widget-new-grid';
	$items = $block->getProductCollection()->getItems();
	?>
	<div class="block widget block-products-by-category grid">
		<div class="block-title">
			<strong role="heading" aria-level="2"><?= $block->escapeHtml($block->getTitle()) ?></strong>
		</div>
		<div class="block-content">
			<div class="products-grid grid">
				<ol class="product-items <?php echo $type ?>">
					<?php foreach ($items as $_item) :?>
						<li class="product-item">
							<div class="product-item-info">
								<a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
								   class="product-item-photo">
									<?= $block->getImage($_item, 'category_page_grid')->toHtml() ?>
								</a>
								<div class="product-item-details">
									<strong class="product-item-name">
										<a title="<?= $block->escapeHtml($_item->getName()) ?>"
										   href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
										   class="product-item-link">
											<?= $block->escapeHtml($_item->getName()) ?>
										</a>
									</strong>
									<?= $block->getProductPriceHtml($_item, $type) ?>
								</div>
							</div>
						</li>
					<?php endforeach ?>
				</ol>
			</div>
		</div>
	</div>
<?php endif;?>