<div class="widget widget-multiple-carousel left"
     loading="lazy"
     data-eloom-widget data-uri="/eloomwidgets/carousel/multiple"
     data-params='<?= $this->getJsonConfig()?>'>
	<div class="loader-spinners">
		<span class="loader-spinners__child"></span>
		<span class="loader-spinners__child"></span>
		<span class="loader-spinners__child"></span>
		<span class="loader-spinners__child"></span>
	</div>
</div>