<div class="block widget block-products products carousel"
     loading="lazy"
     data-eloom-widget data-uri="/eloomwidgets/product/category"
		 data-params='<?= $this->getJsonConfig()?>'>
	<div class="loader-spinners">
		<span class="loader-spinners__child"></span>
		<span class="loader-spinners__child"></span>
		<span class="loader-spinners__child"></span>
		<span class="loader-spinners__child"></span>
	</div>
</div>