<?php
use Magento\Framework\App\Action\Action;

/** @var $block \Eloom\Widgets\Block\Widget\NewProduct */
?>
<?php if ($block->getProductCollection() && $block->getProductCollection()->getSize()): ?>
	<?php
	$type = 'widget-product-grid';
	$items = $block->getProductCollection()->getItems();
	?>
	<div class="block-title">
		<strong role="heading" aria-level="2"><?php echo $block->escapeHtml(__('New Products')) ?></strong>
	</div>
	<div class="block-content">
			<div class="products-grid grid">
				<ol class="product-items <?php echo $type ?>">
					<?php foreach ($items as $_item) : ?>
						<li class="product-item">
							<div class="product-item-info">
								<a href="<?php echo $block->escapeUrl($block->getProductUrl($_item)) ?>"
								   class="product-item-photo">
									<?php echo $block->getImage($_item, 'new_products_content_widget_grid')->toHtml() ?>
								</a>
								<div class="product-item-details">
									<strong class="product-item-name">
										<a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
										   href="<?php echo $block->escapeUrl($block->getProductUrl($_item)) ?>"
										   class="product-item-link">
											<?php echo $block->escapeHtml($_item->getName()) ?>
										</a>
									</strong>
									<?= $block->getProductPriceHtml($_item, $type) ?>
								</div>
							</div>
						</li>
					<?php endforeach ?>
				</ol>
			</div>
		  <?= $block->getPagerHtml() ?>
		</div>
<?php endif; ?>